#!/bin/bash

# Azure Landing Zone Deployment Script
# This script automates the deployment of the Azure Landing Zone

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    print_info "Checking prerequisites..."

    # Check Terraform
    if ! command -v terraform &> /dev/null; then
        print_error "Terraform is not installed. Please install Terraform first."
        exit 1
    fi

    # Check Azure CLI
    if ! command -v az &> /dev/null; then
        print_error "Azure CLI is not installed. Please install Azure CLI first."
        exit 1
    fi

    # Check Azure login
    if ! az account show &> /dev/null; then
        print_error "Not logged in to Azure. Please run 'az login' first."
        exit 1
    fi

    print_info "All prerequisites met!"
}

# Setup backend storage
setup_backend() {
    print_info "Setting up Terraform backend storage..."

    read -p "Do you want to create a new storage account for Terraform state? (y/n): " create_backend

    if [[ "$create_backend" == "y" ]]; then
        read -p "Enter resource group name (default: rg-terraform-state): " rg_name
        rg_name=${rg_name:-rg-terraform-state}

        read -p "Enter storage account name (leave empty for auto-generated): " storage_name
        if [[ -z "$storage_name" ]]; then
            storage_name="stterraform$(openssl rand -hex 4)"
        fi

        read -p "Enter location (default: eastus): " location
        location=${location:-eastus}

        container_name="tfstate"

        print_info "Creating resource group..."
        az group create --name "$rg_name" --location "$location"

        print_info "Creating storage account..."
        az storage account create \
            --resource-group "$rg_name" \
            --name "$storage_name" \
            --sku Standard_LRS \
            --encryption-services blob \
            --min-tls-version TLS1_2 \
            --allow-blob-public-access false

        account_key=$(az storage account keys list \
            --resource-group "$rg_name" \
            --account-name "$storage_name" \
            --query '[0].value' -o tsv)

        print_info "Creating blob container..."
        az storage container create \
            --name "$container_name" \
            --account-name "$storage_name" \
            --account-key "$account_key"

        # Create backend.tfvars
        cat > backend.tfvars <<EOF
resource_group_name  = "$rg_name"
storage_account_name = "$storage_name"
container_name       = "$container_name"
key                  = "landing-zone.tfstate"
EOF

        print_info "Backend configuration saved to backend.tfvars"
        print_info "Storage Account: $storage_name"
    else
        if [[ ! -f "backend.tfvars" ]]; then
            print_error "backend.tfvars not found. Please create it or choose to create a new backend."
            exit 1
        fi
    fi
}

# Configure variables
configure_variables() {
    print_info "Configuring deployment variables..."

    if [[ -f "terraform.tfvars" ]]; then
        read -p "terraform.tfvars already exists. Overwrite? (y/n): " overwrite
        if [[ "$overwrite" != "y" ]]; then
            print_info "Using existing terraform.tfvars"
            return
        fi
    fi

    read -p "Enter environment name (dev/staging/prod): " environment
    environment=${environment:-dev}

    read -p "Enter Azure region (default: eastus): " location
    location=${location:-eastus}

    read -p "Enable Azure Firewall? (y/n, default: y): " enable_firewall
    if [[ "$enable_firewall" == "n" ]]; then
        enable_firewall="false"
    else
        enable_firewall="true"
    fi

    read -p "Enable VPN Gateway? (y/n, default: n): " enable_vpn
    if [[ "$enable_vpn" == "y" ]]; then
        enable_vpn="true"
    else
        enable_vpn="false"
    fi

    read -p "Enable Microsoft Defender for Cloud? (y/n, default: y): " enable_defender
    if [[ "$enable_defender" == "n" ]]; then
        enable_defender="false"
    else
        enable_defender="true"
    fi

    # Create terraform.tfvars
    cat > terraform.tfvars <<EOF
# Auto-generated by deploy.sh

environment = "$environment"
location    = "$location"

root_management_group_name = "Organization Root"
root_management_group_id   = "org-root"

hub_vnet_address_space = ["10.0.0.0/16"]

spoke_vnets = {
  "workload1" = {
    name          = "vnet-workload1"
    address_space = ["10.1.0.0/16"]
    subnets = {
      "app" = {
        address_prefix    = "10.1.1.0/24"
        service_endpoints = ["Microsoft.Storage", "Microsoft.KeyVault"]
      }
      "data" = {
        address_prefix    = "10.1.2.0/24"
        service_endpoints = ["Microsoft.Sql", "Microsoft.Storage"]
      }
    }
  }
}

enable_azure_firewall     = $enable_firewall
enable_vpn_gateway        = $enable_vpn
log_retention_days        = 30
enable_defender_for_cloud = $enable_defender

tags = {
  Project     = "Azure Landing Zone"
  CostCenter  = "IT"
  Environment = "$environment"
}
EOF

    print_info "Variables configured and saved to terraform.tfvars"
}

# Deploy infrastructure
deploy() {
    print_info "Initializing Terraform..."
    terraform init -backend-config=backend.tfvars

    print_info "Validating configuration..."
    terraform validate

    print_info "Creating deployment plan..."
    terraform plan -out=tfplan

    print_warning "Review the plan above carefully."
    read -p "Do you want to proceed with deployment? (yes/no): " proceed

    if [[ "$proceed" != "yes" ]]; then
        print_warning "Deployment cancelled."
        exit 0
    fi

    print_info "Deploying infrastructure..."
    terraform apply tfplan

    print_info "Saving outputs..."
    terraform output > deployment-outputs.txt

    print_info "Deployment complete!"
    print_info "Outputs saved to deployment-outputs.txt"
}

# Main execution
main() {
    echo ""
    echo "======================================"
    echo "  Azure Landing Zone Deployment"
    echo "======================================"
    echo ""

    check_prerequisites
    setup_backend
    configure_variables

    echo ""
    print_info "Ready to deploy!"
    echo ""

    deploy

    echo ""
    print_info "Next steps:"
    echo "  1. Review created resources in Azure Portal"
    echo "  2. Configure firewall rules as needed"
    echo "  3. Set up RBAC assignments"
    echo "  4. Review security recommendations"
    echo "  5. Configure monitoring alerts"
    echo ""
}

# Run main function
main
